# docker-compose up -d --build
# docker exec -it  cyrus-docker bash

version: '3'
services:
    impad:
        container_name: cyrus-docker
        restart: always
        build:
            context: .
            args:
                - mailboxuser=${mailboxuser}
                - mailboxpassword=${mailboxpassword}
                - cyruspassword=${cyruspassword}

        volumes:
            - /richi/Privat/Data/Cyrus/lib/imap:/var/lib/imap
            - /richi/Privat/Data/Cyrus/spool/imap:/var/spool/imap
        ports:
            - "143:143"
        hostname: cyrus

networks:
   default:
       external:
          name: RichiNet
