# docker-compose up -d --build
# docker exec -it  cyrus-docker bash

version: '3'
services:
    impad:
        container_name: cyrus-docker
        restart: always
        build:
            context: .
            args:
                - mailboxuser1=${mailboxuser1}
                - mailboxpassword1=${mailboxpassword1}
                - mailboxuser2=${mailboxuser2}
                - mailboxpassword2=${mailboxpassword2}
                - cyruspassword=${cyruspassword}

        #volumes:
        #    - /richi/Privat/Data/Cyrus/lib/imap:/var/lib/imap
        #    - /richi/Privat/Data/Cyrus/spool/imap:/var/spool/imap
        ports:
            - "143:143"
        hostname: cyrus
        cap_add:
            - SYS_ADMIN
            - SYSLOG
        #security_opt:
        #    - seccomp:unconfined
        # this is needed to allow syslog-ng to write logs
        privileged: true
        
networks:
   default:
       external:
          name: RichiNetXps
