# docker-compose up -d --build
# docker exec -it  cyrus-docker bash

version: '3'
services:
    impad:
        container_name: cyrus-docker
        restart: always
        build:
            context: .
        #uncomment the next lines to have the container use external directories for it's data 
        #volumes:
        #    - /richi/Privat/Data/Cyrus/lib/imap:/var/lib/imap
        #    - /richi/Privat/Data/Cyrus/spool/imap:/var/spool/imap
        ports:
            - "143:143"
        hostname: cyrus
        cap_add:
            - SYS_ADMIN
            - SYSLOG
        # this is needed to allow syslog-ng to write logs
        privileged: true

